### ISSUE TITLE
Atom Boolean

### ISSUE THREAD

**Issue by banditelol** [otakbeku/elixir-bnf#1]
Berdasarkan ini 
![image](https://user-images.githubusercontent.com/5263688/96621373-c0456d00-1332-11eb-8a67-c32619df32ef.png)
Atom `:true` sama `:false` teh bisa dianggap boolean, jadi kalau yang ini diubah jadi

`<boolean> ::= true | false | :true | :false`

gimana?

https://github.com/otakbeku/elixir-bnf/blob/866f5dffe6fe721a67b968943a4874a29ccf9d1d/basic-type.bnf#L31

**Comment by otakbeku** [comment]
diubah karena sebenernya mereka menghasilkan nilai yang sama begitu ya? Kalo dari rule atom-nya gimana? Jaidnya gini

`<atom> ::= :<boolean> | ... `

**Comment by otakbeku** [comment]
![image](https://user-images.githubusercontent.com/13921545/96623182-2df29880-1335-11eb-817b-e7159b2ed7ba.png)
karena itu sih sebenernya

**Comment by banditelol** [comment]
kalau mau assign yang di atom, mending
`<atom> ::= nil | <boolean> | ...`
karena `:<boolean>` teh udah di cover sama rule yang lainnya di `<atom>` sih


terus yang `<boolean> := :true | :false | ...` teh menurut urang perlu, soalnya emang elixir ngetreat atom :false dan :true sebagai boolean 
![image](https://user-images.githubusercontent.com/5263688/96663557-13dba900-137b-11eb-88a2-4f80d7f90b56.png)

**Comment by otakbeku** [comment]
hmmmm bisa saling ditranslasi gitu ya? Woke penulisan rule `<atom>` pake ini aja berarti
`<atom>::= nil | :<boolean>| ...`
