### ISSUE TITLE
Cascading Definisi Angka

### ISSUE THREAD

**Issue by banditelol** [otakbeku/elixir-bnf#3]
Karena banyak angka yang berulang, gimana kalau dibuat definisi angkanya cascading
```
<binary_digit> ::= 0 | 1 
<octal_digit> ::= <binary_digit> | 2 | 3 | 4 | 5 | 6 | 7 
<decimal_digit>::= <octal_digit> | 8 | 9 
<hexadecimal_digit> ::= <decimal_digit> | A | B | C | D | E | F 
```
jadi kalau butuh angka biasa kita ambilnya dari <decimal_digit> atau <decimal>

Tambah lagi angka di elixir teh boleh diawalin sama 0 walaupun ga penting, jadi ini teh valid di elixir:
```
iex-nonode@nohost-(21) | ➤➤➤ 00001
1
iex-nonode@nohost-(22) | ➤➤➤ 0.01000
0.01
```
jadi 0 dan angka lainnya ga dipisah ga masalah

https://github.com/otakbeku/elixir-bnf/blob/866f5dffe6fe721a67b968943a4874a29ccf9d1d/basic-type.bnf#L5-L11

**Comment by otakbeku** [comment]
oh iya lupa deng bisa. Iya salah rulenya. Yang ga bisa itu kalo langsung titik kayak python. Thanks dit!
Kalo format cascading rule pas nuruninnya jadi banyak ga sih?

**Comment by banditelol** [comment]
oiya ding trade-offnya gitu, 
berarti mending gini aja ya
```
 <binary_digit> ::= 0 | 1  
 <octal_digit> ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7  
 <decimal_digit> ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9  
 <hexadecimal_digit> ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | A | B | C | D | E | F
 <decimal> ::= <decimal_digit><decimal>
```

**Comment by otakbeku** [comment]
iyap. Yang hexadecimal tuh penulisannya emang bisa angka sebelum huruf" itu ya? Urang perlu liat lagi
