### ISSUE TITLE
Refining String

### ISSUE THREAD

**Issue by banditelol** [otakbeku/elixir-bnf#4]
[Dari Dokumentasi Soal Escape Sequence](https://elixir-lang.org/getting-started/sigils.html#interpolation-and-escaping-in-string-sigils)
![image](https://user-images.githubusercontent.com/5263688/96622955-d0f6e280-1334-11eb-8a7a-9a2b0295e3d9.png)
ada beberapa escape sequence yang perlu dimasukin
```
<string>::="<string_term>"
<string_term> ::= ' | <alpha>|<decimal>|<special_characters>|<escape_sequence>|<string_interpolation>|<string_term><string_term>
<escape_sequence> ::= \<escape_char> | \x<decimal_digit><decimal_digit> | \x<decimal_digit><decimal_digit> | \u<decimal_digit><decimal_digit><decimal_digit><decimal_digit> | \u{<decimal>} |
<escape_char> ::= ...
```
Sama namanya urang propose jadi `string_term`, karena [`char_list` teh ada lagi di elixir](https://elixir-lang.org/getting-started/sigils.html#char-lists)

yang belum dipropose disini
- [x] Escape Charnya apa aja
- [x] String Interpolation
- [ ] Tell Me

https://github.com/otakbeku/elixir-bnf/blob/866f5dffe6fe721a67b968943a4874a29ccf9d1d/basic-type.bnf#L38-L41

**Comment by otakbeku** [comment]
Oh iya urang lupa ga notice ada char_list. Pake single quote. Soal `string` jadi `string_term` boleh dit. Soal escape char, string interpolation etc itu nanti urang coba cari lagi dokumentasinya. Nice dit. Sementara open dulu, nanti resourcenya bisa dilempar kesini dulu buat dibahas

**Comment by banditelol** [comment]
wokeh, ini coba urang lengkapin sama resource docsnya, terus urang bikin PR biar direview bareng2 gmana?

**Comment by otakbeku** [comment]
boleh juga kalo itu dit
